version: "3.8"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - api
      - front
    depends_on:
      - front
      - api
  front:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./front
    volumes:
      - /front/node_modules
      - ./front:/front
    ports:
      - 8085:8085
  api:
    build:
      context: ./platform
    ports:
      - 8084:8084