version: "3.8"
services:
  front:
    build: 
      dockerfile: Dockerfile.prod
      context: ./front
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./front/nginx/:/etc/nginx/conf.d/:ro
      - ./front/nginx/ssl/serdar.live/:/etc/ssl/serdar.live
  api:
    build:
      context: ./platform
    ports:
      - 8081:8081
