version: "3.8"
services:
  front:
    build: 
      dockerfile: Dockerfile.prod
      context: ./front
    ports:
      - 8085:8085
  api:
    build:
      context: ./platform
    ports:
      - 8084:8084
