FROM node:18.14.1-alpine3.17 as build
WORKDIR /front
COPY package.json .
RUN yarn
COPY . .
RUN yarn run build

FROM nginx:stable-alpine
EXPOSE 80
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /front/dist /usr/share/nginx/html